# Generated by Django 2.2.16 on 2022-05-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220513_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={},
        ),
    ]
